# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b12aa32e322e34e6df0a4ed8b99b8f8dc24921a4722075e00fdd2c487ca006e91acd70d6693130106638bb39c66f2fb9423ce0071ece029855479ad5aab0d502

test:
  secret_key_base: 41657d26b9026fa78979e7c1473b18085a6141ea29970a91ad47aedbace2d372d57933f561f887476e1d4bccd751f64efc84354f5c20b480432bd9d36247ec22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
